[pytest]
testpaths = tests/click tests/unit
addopts = -q --cov=app --cov-report=term-missing
filterwarnings =
	ignore:datetime\.datetime\.utcfromtimestamp\(\) is deprecated.*:DeprecationWarning
	ignore:ast\.Str is deprecated.*:DeprecationWarning
	ignore:Attribute s is deprecated.*:DeprecationWarning
